### PR TITLE
Made compilestatic command Django 1.10 compatible

### PR DESCRIPTION
**Pull request by mpauly**
NoArgsCommand was removed in Django 1.10 and thus compilestatic was not working - I updated to BaseCommand, now the command is working for me under 1.10 as it was before

### CODE REVIEW

**Comment by andreyfedoseev** [comment]
Thank you for your contribution!

Could you extend your pull requests by adding Django 1.10 configuration to `tox.ini` to ensure that it passes all the tests and add yourself to the list of contributors in `AUTHORS`?

**Comment by mpauly** [comment]
Alright, now all tests apart from the Django 1.6 and Django 1.7 tests work - is compatibility with them still required?
Sorry for the mess in the commits, I haven't worked with tox much before

**Comment by andreyfedoseev** [comment]
> Alright, now all tests apart from the Django 1.6 and Django 1.7 tests work - is compatibility with them still required?

Yes, I'd like to keep it compatible with Django 1.6/1.7 for a while.

**Comment by mpauly** [comment]
Now it should also work with Django 1.6 and 1.7 - I believe the Django 1.6 tests fail due to pytest-django dropping Django 1.6 support.

**Pull request merged**
