### PR TITLE
Fixed for Windows using.

### PR DESCRIPTION
**Pull request by stasdavydov**
I found os path related issues (with posixpath) when run the code on Windows host. There was also separator hardcoded "/" issue.

### CODE REVIEW

**Comment by andreyfedoseev** [comment]
`posixpath` is used by design. You're supposed to use `/` even on Windows when, like `path/to/styles.scss|compile` and it should work fine. Whenever `static_precompiler` needs to work with files on filesystem, `os.path` is used.

**Comment by andreyfedoseev** [comment]
@stasdavydov could you check if the current `master` branch works for you? I've added Python 3.5 support and fix the potential file encoding problems.

**Comment by andreyfedoseev** [comment]
@stasdavydov Have you seen my previous comment?

**Comment by stasdavydov** [comment]
Hi! Sorry, I didn't check yet but will do soon.

**Pull request closed without merging**
