### PR TITLE
Removed comments on SASS/SCSS from source before call find_dependencies

### PR DESCRIPTION
**Pull request by Drieger**

### CODE REVIEW

**Comment by andreyfedoseev** [comment]
Thank you for your contribution.

Could you remove `@pytest.mark.xfail` from `test_strip_comment` function to make sure that your implementation passes the tests?

**Comment by andreyfedoseev** [comment]
It seems that the tests are failing: https://circleci.com/gh/andreyfedoseev/django-static-precompiler/137?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Drieger** [comment]
Yeah! I saw, its mainly whitespace and newline issues, I'm correcting it

**Comment by Drieger** [comment]
Ok fixed the issues. Its is removing every leading whitespace before comment start

**Comment by andreyfedoseev** [comment]
Great work, thanks!

**Pull request merged**
