### PR TITLE
Adds Django 3.0 and 3.1 tested compatibility

### LINKED ISSUE #124: Django 3.0
Hello.
Django dropped support for Python 2 in version 2.0 and now with version 3.0 it drops support also for Python 3 compatibility APIs.
**django.utils.six** is no longer available in Django 3.0. This project should switch to six library or drop compatibility layer as well.

### PR DESCRIPTION
**Pull request by BarnabasSzabolcs**
Makes PR#125 "Stop using django.utils.six" progressively stop using six, so the code stays compatible with old versions.

Closes #124

Ref: https://github.com/andreyfedoseev/django-static-precompiler/pull/125
Thanks to: @cafehaine

### CODE REVIEW

**Comment by BarnabasSzabolcs** [comment]
Ok, guys, can you please help how to add python3.6 tests?

**Comment by BarnabasSzabolcs** [comment]
Finally! All tests are green, tests now expand to all the newest versions, with python 3.6.

**Comment by BarnabasSzabolcs** [comment]
@andreyfedoseev can you please merge this into django-static-precompiler, and put up a new version into pip?

**Comment by andreyfedoseev** [comment]
@BarnabasSzabolcs 

Thank you for bringing my attention to this issue. I just released version 2.0 which adds support for Django 3.0 and 3.1

**Comment by BarnabasSzabolcs** [comment]
Thanks Andrey for merging!

**Pull request closed without merging**
