### PR TITLE
Include exclude files

### PR DESCRIPTION
**Pull request by mpauly**
This adds two options that allow to include or exclude specific files:

STATIC_PRECOMPILER_EXCLUDED_FILES - this settings allows to give a list of files to exclude from the compilation
STATIC_PRECOMPILER_INCLUDED_FILES - if given only files matching the pattern in this list will be compiled

This for example is useful if one keeps a full installation of say Twitter's bootstrap in the static folder and does not want to compile it every time one executes the management command.

I also added a test for the two new options.

Please let me know if you are willing to merge this feature,
cheers, Martin

### CODE REVIEW

**Comment by andreyfedoseev** [comment]
Thank you for your contribution. I don't quite the use case though.

> This for example is useful if one keeps a full installation of say Twitter's bootstrap in the static folder and does not want to compile it every time one executes the management command.

`static_precompiler` is supposed to compile files once and re-compile them only if they've been changed. If you never change Bootstrap's source files then they shouldn't be re-compiled every time you execute the management command. If they are indeed re-compiled every time this should be considered a bug.

**Comment by mpauly** [comment]
In our case ´static_precompiler´ tries to compile all files in the bootstrap directory using `less`, however plenty of them fail to compile as they are just meant to be included into the main bootstrap files and not to be compiled individually. The compilation fails and no css file is generated. Thus on the next run of the management command `static_precompiler` tries to compile these files again and again failes. 
By excluding the above mentioned files I could avoid plenty of error messages of files not being compiled using the management command.

**Comment by mpauly** [comment]
@andreyfedoseev Any update on this?

**Comment by andreyfedoseev** [comment]
@mpauly 

Sorry for the late reply. I understand your use case now but I still hesitate over the proposed solution. 

Would the following work for you:

1. Add underscore prefix to the files that are impored in `bootstrap.less`: `_alerts.less`, `_buttons.less` and so on.
2. Update `@import` directives `bootstrap.less` to include underscores

This would prevent static precompiler from compiling those files when the management command is run.

This approach is very common in SASS/SCSS (see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#Partials__partials). If you used SASS/SCSS the second step (updating `bootstrap.scss`) wouldn't be necessary.

Even though partials aren't implemented in Less (see see https://github.com/less/less.js/issues/2295), static precompiler respects the underscore prefix in `.less` file names and doesn't try compile them when the management command is run.

**Comment by mpauly** [comment]
Hey,
that in principle should work, however is not very convenient in our case. 
However I understand that you do not want to include all the extra logic for our use case. How about adding something like
`if self.exclude_file(path): continue` and then just adding a method `exclude_file()` that always returns False in the default implementation, but allows for easy modification of the default command? In that case I could rewrite the command for our case without rewriting everything. Additionally that might also cover other use cases in the future. What do you think?

**Comment by andreyfedoseev** [comment]
@mpauly 

If you don't mind creating a custom compiler based on `static_precompiler.compilers.LESS`, you can just override the existing `should_compile` method and add your exclusion logic there. Then you can use `STATIC_PRECOMPILER_COMPILERS` setting to register your custom compiler, see http://django-static-precompiler.readthedocs.io/en/stable/#general-settings

**Comment by mpauly** [comment]
Perfect, this seems to be the best solution - in that case it won't be necessary to merge this. I'll close this MR.

**Pull request closed without merging**
